import type { ActivityEntry, MemberSeed, ProjectSeed, TaskSeed } from './types';

export const memberSeeds: MemberSeed[] = [
  {
    id: 'maya',
    name: 'Maya Chen',
    initials: 'MC',
    role: 'Product design',
    color: '#7c3aed',
    capacity: 32,
    online: true,
  },
  {
    id: 'leo',
    name: 'Leo Martin',
    initials: 'LM',
    role: 'Engineering',
    color: '#0284c7',
    capacity: 36,
    online: true,
  },
  {
    id: 'sana',
    name: 'Sana Patel',
    initials: 'SP',
    role: 'Growth',
    color: '#db2777',
    capacity: 28,
    online: false,
  },
  {
    id: 'noah',
    name: 'Noah Williams',
    initials: 'NW',
    role: 'Engineering',
    color: '#059669',
    capacity: 34,
    online: true,
  },
  {
    id: 'you',
    name: 'Alex Morgan',
    initials: 'AM',
    role: 'Workspace lead',
    color: '#ea580c',
    capacity: 30,
    online: true,
  },
];

export const projectSeeds: ProjectSeed[] = [
  { id: 'launch', name: 'Product launch', icon: '✦', color: '#7c3aed' },
  { id: 'website', name: 'Website refresh', icon: '◈', color: '#0284c7' },
  { id: 'mobile', name: 'Mobile app', icon: '◇', color: '#059669' },
  { id: 'growth', name: 'Growth experiments', icon: '↗', color: '#db2777' },
];

export const taskSeeds: TaskSeed[] = [
  {
    id: 'OR-241',
    projectId: 'launch',
    title: 'Finalize launch positioning',
    description:
      'Turn the customer research into one crisp narrative for the launch page and sales enablement.',
    status: 'in-progress',
    priority: 'urgent',
    assigneeId: 'sana',
    dueOffset: 1,
    estimateHours: 6,
    tags: ['launch', 'copy'],
    checklist: [
      { id: 'a', label: 'Review research themes', done: true },
      { id: 'b', label: 'Draft positioning statement', done: true },
      { id: 'c', label: 'Get stakeholder sign-off', done: false },
    ],
    comments: [
      {
        id: 'c1',
        authorId: 'maya',
        body: 'The research summary is attached. The simplicity theme is very strong.',
        createdAt: 'Yesterday, 4:32 PM',
      },
    ],
  },
  {
    id: 'OR-242',
    projectId: 'launch',
    title: 'Record product walkthrough',
    description: 'Capture a focused three-minute walkthrough for the launch.',
    status: 'backlog',
    priority: 'high',
    assigneeId: 'you',
    dueOffset: 4,
    estimateHours: 5,
    tags: ['video'],
  },
  {
    id: 'OR-243',
    projectId: 'launch',
    title: 'Production readiness review',
    description: 'Confirm observability, rollback, and support ownership.',
    status: 'review',
    priority: 'urgent',
    assigneeId: 'leo',
    dueOffset: 0,
    estimateHours: 4,
    tags: ['release', 'engineering'],
    checklist: [
      { id: 'a', label: 'Load test complete', done: true },
      { id: 'b', label: 'Rollback rehearsed', done: false },
    ],
  },
  {
    id: 'OR-244',
    projectId: 'launch',
    title: 'Publish migration guide',
    description: 'Document the upgrade path and common compatibility cases.',
    status: 'done',
    priority: 'normal',
    assigneeId: 'noah',
    dueOffset: -2,
    estimateHours: 7,
    tags: ['docs'],
  },
  {
    id: 'OR-198',
    projectId: 'website',
    title: 'Build responsive navigation',
    description:
      'Implement desktop and mobile navigation from the approved system.',
    status: 'in-progress',
    priority: 'high',
    assigneeId: 'leo',
    dueOffset: 2,
    estimateHours: 8,
    tags: ['frontend', 'responsive'],
  },
  {
    id: 'OR-199',
    projectId: 'website',
    title: 'Approve homepage visual system',
    description: 'Resolve the remaining typography and illustration decisions.',
    status: 'review',
    priority: 'normal',
    assigneeId: 'maya',
    dueOffset: 1,
    estimateHours: 4,
    tags: ['design'],
  },
  {
    id: 'OR-200',
    projectId: 'website',
    title: 'Migrate customer stories',
    description: 'Move the case-study library into the new content model.',
    status: 'backlog',
    priority: 'low',
    assigneeId: 'sana',
    dueOffset: 8,
    estimateHours: 10,
    tags: ['content'],
  },
  {
    id: 'OR-201',
    projectId: 'website',
    title: 'Set performance budgets',
    description: 'Add CI budgets for LCP, JavaScript, fonts, and images.',
    status: 'done',
    priority: 'high',
    assigneeId: 'noah',
    dueOffset: -5,
    estimateHours: 3,
    tags: ['performance'],
  },
  {
    id: 'OR-312',
    projectId: 'mobile',
    title: 'Offline mutation queue',
    description:
      'Queue edits locally and reconcile them when connectivity returns.',
    status: 'in-progress',
    priority: 'urgent',
    assigneeId: 'noah',
    dueOffset: -1,
    estimateHours: 12,
    tags: ['offline', 'sync'],
  },
  {
    id: 'OR-313',
    projectId: 'mobile',
    title: 'Notification preferences',
    description: 'Let members choose push and email notification categories.',
    status: 'backlog',
    priority: 'normal',
    assigneeId: 'leo',
    dueOffset: 10,
    estimateHours: 8,
    tags: ['settings'],
  },
  {
    id: 'OR-314',
    projectId: 'mobile',
    title: 'Test tablet breakpoints',
    description:
      'Verify navigation and task detail layouts across tablet sizes.',
    status: 'review',
    priority: 'normal',
    assigneeId: 'maya',
    dueOffset: 3,
    estimateHours: 4,
    tags: ['qa', 'responsive'],
  },
  {
    id: 'OR-315',
    projectId: 'mobile',
    title: 'Ship biometric unlock',
    description: 'Complete device authentication and fallback behavior.',
    status: 'done',
    priority: 'high',
    assigneeId: 'noah',
    dueOffset: -4,
    estimateHours: 9,
    tags: ['security'],
  },
  {
    id: 'OR-401',
    projectId: 'growth',
    title: 'Activation cohort dashboard',
    description:
      'Compare activation behavior by acquisition source and persona.',
    status: 'in-progress',
    priority: 'high',
    assigneeId: 'sana',
    dueOffset: 3,
    estimateHours: 7,
    tags: ['analytics'],
  },
  {
    id: 'OR-402',
    projectId: 'growth',
    title: 'Invite flow experiment',
    description: 'Test contextual team invites after the first completed task.',
    status: 'backlog',
    priority: 'normal',
    assigneeId: 'you',
    dueOffset: 6,
    estimateHours: 5,
    tags: ['experiment'],
  },
  {
    id: 'OR-403',
    projectId: 'growth',
    title: 'Analyze trial conversion',
    description: 'Identify the behaviors most correlated with paid conversion.',
    status: 'done',
    priority: 'normal',
    assigneeId: 'sana',
    dueOffset: -6,
    estimateHours: 6,
    tags: ['analytics'],
  },
];

export const activitySeeds: Omit<ActivityEntry, 'id'>[] = [
  {
    actorId: 'leo',
    icon: '→',
    text: 'moved Production readiness review to Review',
    createdAt: '12 min',
  },
  {
    actorId: 'maya',
    icon: '✓',
    text: 'completed Approve homepage visual system checklist',
    createdAt: '38 min',
  },
  {
    actorId: 'sana',
    icon: '+',
    text: 'commented on Finalize launch positioning',
    createdAt: '1 hr',
  },
  {
    actorId: 'noah',
    icon: '●',
    text: 'completed Ship biometric unlock',
    createdAt: '3 hr',
  },
];
